Repository FocusNFe/api-doc, pull requests merged in 2023-04, with the labels that each got.

#1 Focus Customizations
  .github/workflows/deploy.yml
  README.md
  config.rb
  lib/nesting_unique_head.rb
  source/images/diagrama_enviador_electron_2.png
  source/images/logo.png
  source/images/logo.svg
  source/includes/_backups.md
  source/includes/_cep.md
  source/includes/_cfop.md
  source/includes/_cnae.md
  source/includes/_cnpjs.md
  source/includes/_comunicador-focus-nfe.md
  source/includes/_cte.md
  source/includes/_email.md
  source/includes/_empresas.md
  source/includes/_errors.md
  source/includes/_github.md
  source/includes/_limite-requisicoes.md
  source/includes/_lote_rps.md
  source/includes/_manifestacao-cte.md
  source/includes/_manifestacao.md
  source/includes/_mdfe.md
  source/includes/_municipios.md
  source/includes/_ncm.md
  source/includes/_nfce.md
  source/includes/_nfe.md
  source/includes/_nfse.md
  source/includes/_nfses-recebidas.md
  source/includes/_webhooks.md
  source/index.html.md
  source/layouts/layout.erb
  source/stylesheets/screen.css.scss
Labels: enhancement

#4 Alterações de artigos e email suporte
  source/index.html.md
Labels: documentation

#3 Corrige imagem na documentação do Comunicador
  source/includes/_comunicador-focus-nfe.md.erb
  source/index.html.md
Labels: bug

#2 Adiciona link para o site a partir da Logo
  source/layouts/layout.erb
Labels: enhancement

#5 Corrige documentação comunicador (migra diff de outro repositório)
  source/includes/_comunicador-focus-nfe.md.erb
Labels: bug, documentation

#6 Encurta Títulos
  source/includes/_github.md
Labels: documentation

#7 Correção de emails de suporte, links e typos
  source/includes/_cfop.md
  source/includes/_cnae.md
  source/includes/_cnpjs.md
  source/includes/_comunicador-focus-nfe.md.erb
  source/includes/_cte.md
  source/includes/_limite-requisicoes.md
  source/includes/_lote_rps.md
  source/includes/_manifestacao-cte.md
  source/includes/_manifestacao.md
  source/includes/_mdfe.md
  source/includes/_municipios.md
  source/includes/_nfce.md
  source/includes/_nfe.md
  source/includes/_nfse.md
  source/includes/_nfses-recebidas.md
  source/index.html.md
Labels: bug
