Repository FocusNFe/api-doc, pull requests merged in 2024-08, with the labels that each got.

#38 Adiciona novos campos da API de CNAEs
  source/includes/_cnae.md
Labels: enhancement

#39 Inclui campo data_incio_recebimento_cte
  source/includes/_empresas.md
Labels: documentation

#40 Corrige documentação de encerramento MDFe
  source/includes/_mdfe.md
Labels: bug
